"""edu_bid knowledge documents

Revision ID: 42c593f9a72b
Revises:
Create Date: 2026-06-02 16:22:43.944964
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "42c593f9a72b"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "edu_bid_knowledge_documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("section", sa.String(length=32), nullable=False),
        sa.Column("track", sa.String(length=16), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("author", sa.String(length=64), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("section", "track", "version", name="uq_knowledge_doc_ver"),
    )
    op.create_index(
        op.f("ix_edu_bid_knowledge_documents_active"),
        "edu_bid_knowledge_documents",
        ["active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_edu_bid_knowledge_documents_section"),
        "edu_bid_knowledge_documents",
        ["section"],
        unique=False,
    )
    op.create_index(
        op.f("ix_edu_bid_knowledge_documents_track"),
        "edu_bid_knowledge_documents",
        ["track"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_edu_bid_knowledge_documents_track"),
        table_name="edu_bid_knowledge_documents",
    )
    op.drop_index(
        op.f("ix_edu_bid_knowledge_documents_section"),
        table_name="edu_bid_knowledge_documents",
    )
    op.drop_index(
        op.f("ix_edu_bid_knowledge_documents_active"),
        table_name="edu_bid_knowledge_documents",
    )
    op.drop_table("edu_bid_knowledge_documents")
    # ### end Alembic commands ###
