"""edu_bid init: runs + decisions

Revision ID: aae63fc0799f
Revises:
Create Date: 2026-06-02 15:44:55.714811
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "aae63fc0799f"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "edu_bid_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("window_bgn", sa.String(length=12), nullable=False),
        sa.Column("window_end", sa.String(length=12), nullable=False),
        sa.Column("run_date", sa.String(length=10), nullable=False),
        sa.Column("collected", sa.Integer(), nullable=False),
        sa.Column("triaged", sa.Integer(), nullable=False),
        sa.Column("dropped_work_type", sa.Integer(), nullable=False),
        sa.Column("dropped_gate", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_edu_bid_runs_run_date"), "edu_bid_runs", ["run_date"], unique=False
    )
    op.create_table(
        "edu_bid_decisions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("track", sa.String(length=16), nullable=False),
        sa.Column("label", sa.String(length=16), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("enriched", sa.Boolean(), nullable=False),
        sa.Column("bid_no", sa.String(length=64), nullable=False),
        sa.Column("bid_ord", sa.String(length=16), nullable=False),
        sa.Column("kind_label", sa.String(length=32), nullable=False),
        sa.Column("stage", sa.String(length=16), nullable=False),
        sa.Column("work_type", sa.String(length=32), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("notice_inst", sa.Text(), nullable=False),
        sa.Column("demand_inst", sa.Text(), nullable=False),
        sa.Column("close_dt", sa.String(length=32), nullable=False),
        sa.Column("opinion_close_dt", sa.String(length=32), nullable=False),
        sa.Column("estimated_price", sa.String(length=32), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("award_method", sa.String(length=128), nullable=False),
        sa.Column("quant_barrier", sa.String(length=16), nullable=False),
        sa.Column("wired_risk", sa.String(length=16), nullable=False),
        sa.Column("axes", sa.JSON(), nullable=False),
        sa.Column("matched_assets", sa.JSON(), nullable=False),
        sa.Column("gate_status", sa.String(length=16), nullable=False),
        sa.Column("gate_reasons", sa.JSON(), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["edu_bid_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_edu_bid_decisions_bid_no"),
        "edu_bid_decisions",
        ["bid_no"],
        unique=False,
    )
    op.create_index(
        op.f("ix_edu_bid_decisions_label"), "edu_bid_decisions", ["label"], unique=False
    )
    op.create_index(
        op.f("ix_edu_bid_decisions_run_id"),
        "edu_bid_decisions",
        ["run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_edu_bid_decisions_track"), "edu_bid_decisions", ["track"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_edu_bid_decisions_track"), table_name="edu_bid_decisions")
    op.drop_index(op.f("ix_edu_bid_decisions_run_id"), table_name="edu_bid_decisions")
    op.drop_index(op.f("ix_edu_bid_decisions_label"), table_name="edu_bid_decisions")
    op.drop_index(op.f("ix_edu_bid_decisions_bid_no"), table_name="edu_bid_decisions")
    op.drop_table("edu_bid_decisions")
    op.drop_index(op.f("ix_edu_bid_runs_run_date"), table_name="edu_bid_runs")
    op.drop_table("edu_bid_runs")
    # ### end Alembic commands ###
