# name: Build codle Prd

# on:
#   push:
#     branches: [main]

# jobs:
#   build:
#     uses: team-monolith-product/tmn-gh-actions/.github/workflows/build_v2.yml@main
#     with:
#       env: prd
#       target: main
#       propertyPath: react.image.tag
#       updateTargets: |
#         {
#           "aws": {
#             "imageName": "jce-ecr-tch-react-all-prd",
#             "valueFilePath": ["codle-react/prd.yaml"]
#           },
#           "ncp": {
#             "registry": "ped-cr-all-prd.ncr.gov-ntruss.com",
#             "imageName": "jce-codle-react",
#             "valueFilePath": ["codle-react/ncloud-prd.yaml"]
#           }
#         }
#     secrets:
#       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#       NCP_ACCESS_KEY_ID: ${{ secrets.NCP_ACCESS_KEY_ID }}
#       NCP_SECRET_KEY: ${{ secrets.NCP_SECRET_KEY }}
#       MACHINE_TOKEN: ${{ secrets.MACHINE_TOKEN }}
#       DOCKER_SECRETS: ${{ secrets.DOCKER_SECRETS }}
