name: Collect Code Review Stats

on:
  schedule:
    - cron: '0 0 * * 1-5'  # 매주 평일 오전 9시(UTC+9)에 실행
  workflow_dispatch:  # 수동 실행 가능

jobs:
  collect_review_stats:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # 10분 타임아웃 설정
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run collect_review_stats.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        run: |
          python collect_review_stats.py --limit-repos 10  # 저장소 개수 제한